server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventories
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: DEBUG

management:
  trace:
    http:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus,env,info,metrics,threaddump,httpexchanges,mappings,gateway
      base-path: /management
  endpoint:
    gateway:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: always
