spring:
  application:
    name: discovery-server
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
management:
  trace:
    http:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus,env,info,metrics,threaddump,httpexchanges,mappings
      base-path: /management
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
